### ISSUE TITLE
missing explanation how to connect via ssh

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-example#3]
I searched a lot but I didn't find a way to connect to any of the running mashines. It seems it awaits some ssh keys to connect.

How can you connect to a started and running vm machine if you are not sargon?

**Comment by rubo77** [comment]
Strange, noow it works, after I pulled the latest changes.

could it be, that this fixed the problem? https://github.com/ffnord/ffnord-example/commit/2aab8ae1ea1e9d8ff29ef156e406ec9c660c0151

**Comment by rubo77** [comment]
Now it deosnt work anymore on gc-gw0 but it works on the VM services. What can I do to debug what is happening when I cannot connect?

**Comment by rubo77** [comment]
I think the problem is, if the puppet scripts are adding stuff to the network configuration, so networking isn't going up, thus you cannot log in via ssh

We should add a standard root password, so you can login from the graphical virtualbox console

**Comment by sargon** [comment]
The usual way is to use:
    vagrant ssh <machine-name> 
When this dosn't work for you, something in your vagrant, virtualbox setup is broken.
